name: deploy-template-app

on: 
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  deploy-template:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'